steps:
- name: 'gcr.io/cloud-builders/docker'
  id: runDockerfile
  args:
  - 'build'
  - '-t'
  - 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:test1'
  - '--file=Dockerfile'
  - '.'
#- name: 'script-runner' 
  #waitFor:
    #- getdocker
  #args: ['bash', '/home/ANT/ANT/bin/ant', '-buildfile', '/home/stk11.5.0/CodeSamples/CustomApplications/Java/AWT_STK_X_Globe_View']
tags: ['testing1.1']
images: ['gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:test1']
#storing artifacts in Cloud Storage
artifacts:
  objects:
    #location: 'gs://testing-stk-cis/cpts423seniorproject'
    location: 'gs://testing-stk-cis/test1'
    paths: ['*.*', '*']
    #paths: ['*.txt', '*.log']



#FROM carlyishere/stk_cis:updated1
#CMD /home/ANT/ANT/bin/ant -buildfile /home/stk11.5.0/CodeSamples/CustomApplications/Java/AWT_STK_X_Globe_View
