steps:
- name: 'gcr.io/cloud-builders/docker'
  id: runDockerfile
  args:
  - 'build'
  - '-t'
  - 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest'
  #- 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:test1'
  - '--file=Dockerfile'
  - '.'
tags: ['testing1.2']
images: ['gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest']
#images: ['gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:test1']
#storing artifacts in Cloud Storage (creates it in Buckets under 'Storage')
artifacts:
  objects:
    #location: 'gs://testing-stk-cis/cpts423seniorproject'
    #location: 'gs://testing-stk-cis/test1'
    location: 'gs://testing-stk-cis/test2'
    paths: ['*.*']
    #paths: ['*.txt', '*.log']


#To store an image as part of your build flow and 
#to display the image in the build results:
#steps:
#- name: 'gcr.io/cloud-builders/docker'
#  id: store image and display build results
#  args: ['push', 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest']
#images: ['gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest']