steps:
- name: 'gcr.io/cloud-builders/docker'
  #args: ['build', '-t', 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:test1', '.']
  args: ['build', '-t', 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:test1', 'LD_LIBRARY_PATH=/home/stk11.5.0/bin', 'STK_INSTALL_DIR=/home/stk11.5.0', 'STK_CONFIG_DIR=/home/user_info/STK11', 'JAVA_HOME=/usr/lib/jvm/java-11-oracle', 'ANT_HOME=/home/ANT/ANT', 'PATH=${ANT_HOME}/bin:${JAVA_HOME}/bin:${PATH}' ,'.']
  #args: ['build', '-t', 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest', '.']
- name: 'script-runner' 
  args: ['bash', '/home/ANT/ANT/bin/ant', '-buildfile', '/home/stk11.5.0/CodeSamples/CustomApplications/Java/AWT_STK_X_Globe_View']
  #args: ['bash', '/home/ANT/ANT/bin/ant', '-buildfile', '/home/stk11.5.0/CodeSamples/CustomApplications/Java/AWT_STK_X_Globe_View', 'ant run']
  #env:
  #- 'LD_LIBRARY_PATH=/home/stk11.5.0/bin'
  #- 'STK_INSTALL_DIR=/home/stk11.5.0'
  #- 'STK_CONFIG_DIR=/home/user_info/STK11'
  #- 'JAVA_HOME=/usr/lib/jvm/java-11-oracle'
  #- 'ANT_HOME=/home/ANT/ANT'
  #- 'PATH=${ANT_HOME}/bin:${JAVA_HOME}/bin:${PATH}'
tags: ['testing1.1']
images: ['gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:test1']
#images: ['gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest']

#storing artifacts in Cloud Storage
artifacts:
  objects:
    #location: 'gs://testing-stk-cis/cpts423seniorproject'
    location: 'gs://testing-stk-cis/test1'
    paths: ['*.txt']
    #paths: ['*.txt', '*.log']


#storing images in Container Registry



#FROM carlyishere/stk_cis:updated1
#CMD /home/ANT/ANT/bin/ant -buildfile /home/stk11.5.0/CodeSamples/CustomApplications/Java/AWT_STK_X_Globe_View
