steps:
- name: 'gcr.io/cloud-builders/docker'
  id: runDockerfile
  volumes:
  - name: 'docker'
    path: '/wd'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:latest'
  - '--file=Dockerfile'
  - '.'
  - name: 'gcr.io/cloud-builders/docker'
  id: runDockerfile
  volumes:
  - name: 'docker'
    path: '/wd'
  args:
  - 'cp'
  - '-t'
  - 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:latest:/home/OrbitalSimulationSuite/NoGraphics/txt.txt'
  - 'txt.txt'
- name: 'gcr.io/cloud-builders/gsutil'
  volumes:
  - name: 'docker'
    path: '/wd'
  args: ['/wd/ls']
tags: ['testing1.2']
images: ['gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:latest']
#storing artifacts in Cloud Storage (creates it in Buckets under 'Storage')
artifacts:
  objects:
    location: 'gs://testing-stk-cis/test2'
    paths: ['/wd/*.*']
    #paths: ['report.txt', 'reportArea.txt']
    #paths: ['*', '*.*']
    
