steps:

- name: 'gcr.io/cloud-builders/gsutil'
  volumes:
  - name: 'docker'
    path: '/wd'
  args: ['ls', 'gs://cpts423seniorproject_cloudbuild']
  
- name: 'gcr.io/cloud-builders/docker'
  id: runDockerfile
  volumes:
  - name: 'docker'
    path: '/wd'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:latest'
  - '--file=Dockerfile'
  - '.'
  
- name: 'gcr.io/cloud-builders/docker'
  id: copyFiles
  volumes:
  - name: 'docker'
    path: '/wd'
  args:
  - 'container'
  - 'ls'
  - 'all'
  #- 'cp'
  #- 'gs://cpts423seniorproject_cloudbuild:/home/OrbitalSimulationSuite/NoGraphics/txt.txt'
  #- 'txt.txt'
  
- name: 'gcr.io/cloud-builders/gsutil'
  volumes:
  - name: 'docker'
    path: '/wd'
  args: ['ls', '/wd']
tags: ['testing1.2']
images: ['gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:latest']
#storing artifacts in Cloud Storage (creates it in Buckets under 'Storage')
artifacts:
  objects:
    location: 'gs://testing-stk-cis/test2'
    paths: ['txt.txt']
    #paths: ['report.txt', 'reportArea.txt']
    #paths: ['*', '*.*']
    
