steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['ls']
- name: 'gcr.io/cloud-builders/docker'
  id: runDockerfile
  args:
  - 'build'
  - '-t'
  - 'gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:latest'
  - '--file=Dockerfile'
  - '.'
tags: ['testing1.2']
images: ['gcr.io/cpts423seniorproject/github.com/carlyott/423dockertest:latest']
#storing artifacts in Cloud Storage (creates it in Buckets under 'Storage')
artifacts:
  objects:
    location: 'gs://testing-stk-cis/test2'
    paths: ['/home/OrbitalSimulationSuite/NoGraphics/*.*']
    #paths: ['report.txt', 'reportArea.txt']
    #paths: ['*', '*.*']
    
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['ls']
